<#
.SYNOPSIS
    Single-source adapter generator for the Baba prompt system.
.DESCRIPTION
    Emits per-platform adapter files from a small, fixed set of sources so no
    platform config is hand-maintained twice:

      Source                              Generated targets
      opencode.jsonc "mcp" block    ->    .mcp.json (tier-1 servers)
                                        ->    .codex/config.toml [mcp_servers] + config
      .opencode/agents/baba-*.md    ->    .claude/agents/<name>.md
      .opencode/commands/*.md       ->    .claude/commands/<name>.md
      BOOTSTRAP.md                  ->    .cursor/rules/bootstrap.mdc (alwaysApply)
                                        ->    .claude/commands/bootstrap.md
                                        ->    .codex/config.toml (full config)

The canonical system files (prompt-system/00-system.md through prompt-system/08-plan-actual-gate.md,
AGENTS.md, README.md, docs/*.md) are NOT inputs to this script. Editing them
and re-running the generator is a deliberate no-op: the adapters only react
to changes in opencode.jsonc and the .opencode/ sources above.

    Generated markdown files carry a GENERATED banner after their frontmatter;
    edits there are overwritten on the next run. .mcp.json is strict JSON and
    cannot carry a banner - treat it as generated by convention. sync.ps1 runs
    this script before every propagation so targets never ship stale mirrors.
.EXAMPLE
    .\generate-adapters.ps1
#>

$ErrorActionPreference = 'Stop'
$scriptDir = Split-Path -Parent $MyInvocation.MyCommand.Path

# Tier-1 servers: no keys required, safe to enable in every project scope.
# Explicit list over discovery - tier membership is a decision, not a guess.
$tier1 = @('context7', 'playwright')

# Tools granted to read-only personas (permission.edit = deny). Personas that
# allow edit omit the tools field entirely and inherit every tool.
$readOnlyTools = 'Read, Grep, Glob, WebFetch, WebSearch'

# Slash commands taking arguments get an autocomplete hint; keyed by command
# file name. Commands absent here take no arguments.
$argHints = @{
    'approve-plan' = '[notes]'
    'baba'         = '<scrummaster|sensei|dev|tester|reviewer> [task]'
    'handoff'      = '[persona] [notes]'
    'phase'        = '<CHECKLIST|DOCS|REVIEW|PLAN|PATCH|...>'
    'verify'       = '[focus]'
    'bootstrap'    = ''
    'reddit-post'  = '[subreddit-override]'
    'arxiv-paper'  = '[arxiv-id-or-url]'
}

$bannerMd   = '<!-- GENERATED by generate-adapters.ps1 - edit .opencode/ sources, not this file. -->'
$bannerToml = '# GENERATED by generate-adapters.ps1 - edit opencode.jsonc, not this section.'

# Cursor rule file extension
$cursorExt = '.mdc'

function Split-Frontmatter {
    param([string]$Text)

    $lines = $Text -replace "`r`n", "`n" -split "`n"
    if ($lines[0].Trim() -ne '---') {
        throw "missing frontmatter opening fence"
    }
    $close = -1
    for ($i = 1; $i -lt $lines.Count; $i++) {
        if ($lines[$i].Trim() -eq '---') { $close = $i; break }
    }
    if ($close -lt 0) { throw 'frontmatter not closed' }

    return @{
        Meta = $lines[1..($close - 1)]
        Body = ($lines[($close + 1)..($lines.Count - 1)] -join "`n").Trim()
    }
}

function Get-MetaValue {
    param([string[]]$Meta, [string]$Key)
    foreach ($line in $Meta) {
        if ($line -match "^$([regex]::Escape($Key))\s*:\s*(.+?)\s*$") {
            return $Matches[1].Trim('"')
        }
    }
    return $null
}

function Get-PermissionEdit {
    param([string[]]$Meta)
    foreach ($line in $Meta) {
        # permission block nests edit under two-space indent
        if ($line -match '^\s+edit\s*:\s*(allow|deny)\s*$') {
            return $Matches[1]
        }
    }
    return $null
}

function Get-SourceMcpServers
{
    $raw = Get-Content -LiteralPath (Join-Path $scriptDir 'opencode.jsonc') -Raw -Encoding UTF8
    $json = ($raw -split "`n" | Where-Object { $_.TrimStart() -notmatch '^//' }) -join "`n"
    try {
        $config = $json | ConvertFrom-Json
    } catch {
        $cleaned = $json -replace ',(\s*[}\]])', '$1'
        $config = $cleaned | ConvertFrom-Json
    }
    if (-not $config.mcp) { throw 'opencode.jsonc has no mcp block' }
    return $config.mcp
}

function New-ClaudeMcpJson
{
    param([object]$Mcp, [string[]]$Names)

    $entries = foreach ($name in $Names) {
        $srv = $Mcp.$name
        if (-not $srv) { throw "tier-1 server '$name' missing from opencode.jsonc" }
        if ($srv.command) {
            $cmd = @($srv.command)
            $rest = @(); if ($cmd.Count -gt 1) { $rest = $cmd[1..($cmd.Count - 1)] }
            $argsJson = (@($rest | ForEach-Object { '"' + ($_ -replace '"', '\"') + '"' }) -join ', ')
            "    `"$name`": {`n        `"command`": `"$($cmd[0])`",`n        `"args`": [$argsJson]`n    }"
        }
        elseif ($srv.url) {
            "    `"$name`": {`n        `"type`": `"http`",`n        `"url`": `"$($srv.url)`"`n    }"
        }
        else {
            throw "server '$name' has neither command nor url"
        }
    }
    return "{`n    `"mcpServers`": {`n" + ($entries -join ",`n") + "`n    }`n}" + "`n"
}

function New-CodexTomlSection
{
    param([object]$Mcp, [string[]]$Names)

    $blocks = foreach ($name in $Names) {
        $srv = $Mcp.$name
        if (-not $srv) { throw "tier-1 server '$name' missing from opencode.jsonc" }
        if ($srv.command) {
            $cmd = @($srv.command)
            $rest = @(); if ($cmd.Count -gt 1) { $rest = $cmd[1..($cmd.Count - 1)] }
            $argsToml = '[' + (($rest | ForEach-Object { '"' + ($_ -replace '"', '\"') + '"' }) -join ', ') + ']'
            "[mcp_servers.$name]`ncommand = `"$($cmd[0])`"`nargs = $argsToml"
        }
        elseif ($srv.url) {
            "[mcp_servers.$name]`nurl = `"$($srv.url)`""
        }
        else {
            throw "server '$name' has neither command nor url"
        }
    }
    return ($blocks -join "`n`n")
}

function Update-CodexToml
{
    param([object]$Mcp, [string[]]$Names)

    $path = Join-Path $scriptDir '.codex\config.toml'
    $text = (Get-Content -LiteralPath $path -Raw -Encoding UTF8) -replace "`r`n", "`n"
    $section = "$bannerToml`n$(New-CodexTomlSection -Mcp $Mcp -Names $Names)`n"

    # Cut at the banner when present - it owns everything to end of file, so
    # reruns can never accumulate stale banners or sections.
    $cut = $text.IndexOf($bannerToml)
    if ($cut -lt 0) { $cut = $text.IndexOf('[mcp_servers.') }
    if ($cut -ge 0) {
        $text = $text.Substring(0, $cut).TrimEnd() + "`n`n" + $section
    }
    else {
        $text = $text.TrimEnd() + "`n`n" + $section
    }
    [System.IO.File]::WriteAllText($path, $text)
}

$count = 0
$mcp = Get-SourceMcpServers

# .mcp.json (strict JSON, no banner possible)
[System.IO.File]::WriteAllText(
    (Join-Path $scriptDir '.mcp.json'),
    (New-ClaudeMcpJson -Mcp $mcp -Names $tier1))
Write-Host 'OK  .mcp.json' -ForegroundColor Green
$count++

# Codex [mcp_servers] section (preserves everything above it)
Update-CodexToml -Mcp $mcp -Names $tier1
Write-Host 'OK  .codex/config.toml [mcp_servers]' -ForegroundColor Green
$count++

# Subagents: .opencode/agents/baba-*.md -> .claude/agents/<name>.md
New-Item -ItemType Directory -Force -Path (Join-Path $scriptDir '.claude\agents') | Out-Null
foreach ($src in Get-ChildItem -Path (Join-Path $scriptDir '.opencode\agents') -Filter 'baba-*.md')
{
    $parts = Split-Frontmatter (Get-Content -LiteralPath $src.FullName -Raw -Encoding UTF8)
    $description = Get-MetaValue $parts.Meta 'description'
    if (-not $description) { throw "$($src.Name): no description" }

    $toolLine = ''
    if ((Get-PermissionEdit $parts.Meta) -eq 'deny')
    {
        $toolLine = "tools: $readOnlyTools`n"
    }

    $out = "---`nname: $([IO.Path]::GetFileNameWithoutExtension($src.Name))`ndescription: $description`n$toolLine---`n`n$bannerMd`n`n$($parts.Body)`n"
    $dest = Join-Path $scriptDir ('.claude\agents\' + $src.Name)
    [System.IO.File]::WriteAllText($dest, $out)
    Write-Host "OK  .claude/agents/$($src.Name)" -ForegroundColor Green
    $count++
}

# Commands: .opencode/commands/*.md -> .claude/commands/*.md
New-Item -ItemType Directory -Force -Path (Join-Path $scriptDir '.claude\commands') | Out-Null
foreach ($src in Get-ChildItem -Path (Join-Path $scriptDir '.opencode\commands') -Filter '*.md')
{
    $stem = [IO.Path]::GetFileNameWithoutExtension($src.Name)
    $parts = Split-Frontmatter (Get-Content -LiteralPath $src.FullName -Raw -Encoding UTF8)
    $description = Get-MetaValue $parts.Meta 'description'
    if (-not $description) { throw "$($src.Name): no description" }

    $hintLine = ''
    if ($argHints.ContainsKey($stem)) {
        $hintLine = "argument-hint: $($argHints[$stem])`n"
    }

    $out = "---`ndescription: $description`n$hintLine---`n`n$bannerMd`n`n$($parts.Body)`n"
    $dest = Join-Path $scriptDir ('.claude\commands\' + $src.Name)
    [System.IO.File]::WriteAllText($dest, $out)
    Write-Host "OK  .claude/commands/$($src.Name)" -ForegroundColor Green
    $count++
}

# Cursor rule: .cursor/rules/bootstrap.mdc (alwaysApply: true)
New-Item -ItemType Directory -Force -Path (Join-Path $scriptDir '.cursor\rules') | Out-Null
$cursorRule = @"
---
alwaysApply: true
description: Enforces mandatory STARTUP fingerprint gate per BOOTSTRAP.md
---
$bannerMd

@BOOTSTRAP.md
"@
[System.IO.File]::WriteAllText(
    (Join-Path $scriptDir '.cursor\rules\bootstrap.mdc'),
    $cursorRule)
Write-Host "OK  .cursor/rules/bootstrap.mdc" -ForegroundColor Green
$count++

# Claude command: .claude/commands/bootstrap.md (auto-attaches 00-system.md)
New-Item -ItemType Directory -Force -Path (Join-Path $scriptDir '.claude\commands') | Out-Null
$claudeBootstrapCmd = @"
---
description: Enforce STARTUP phase - read 00-system.md, emit fingerprint, load all system files
argument-hint: 
---
$bannerMd

@prompt-system/00-system.md
@prompt-system/01-personas.md
@prompt-system/03-output-and-state.md
@prompt-system/04-rubrics.md
@prompt-system/05-impl-style.md
@prompt-system/06-misc.md
@prompt-system/07-protocols.md
@prompt-system/08-plan-actual-gate.md

**MANDATORY**: After reading 00-system.md, emit fingerprint:
\`\`\`
00-system.md fingerprint: <line_count> lines, first_100_chars="<first 100 chars>", last_100_chars="<last 100 chars>", sha256_first_1kb="<hash or N/A>"
\`\`\`

Then load remaining 7 files. No phase output until fingerprint verified.
"@
[System.IO.File]::WriteAllText(
    (Join-Path $scriptDir '.claude\commands\bootstrap.md'),
    $claudeBootstrapCmd)
Write-Host "OK  .claude/commands/bootstrap.md" -ForegroundColor Green
$count++

# Codex config: .codex/config.toml (full config with approval_policy, sandbox_mode, mcp_servers)
$codexConfig = @"
$bannerToml
# Codex CLI configuration for Baba prompt system

approval_policy = "on-request"
sandbox_mode = "workspace-write"

[sandbox_workspace_write]
network_access = true

# Tier-1 MCP servers (no keys required)
$(New-CodexTomlSection -Mcp $mcp -Names $tier1)
"@
$codexPath = Join-Path $scriptDir '.codex\config.toml'
New-Item -ItemType Directory -Force -Path (Join-Path $scriptDir '.codex') | Out-Null
# Preserve existing content above the banner
$existing = ""
if (Test-Path -LiteralPath $codexPath) {
    $existing = (Get-Content -LiteralPath $codexPath -Raw -Encoding UTF8) -replace "`r`n", "`n"
    $cut = $existing.IndexOf($bannerToml)
    if ($cut -ge 0) {
        $existing = $existing.Substring(0, $cut).TrimEnd()
    } else {
        $cut = $existing.IndexOf('[mcp_servers.')
        if ($cut -ge 0) {
            $existing = $existing.Substring(0, $cut).TrimEnd()
        }
    }
    if ($existing) { $existing += "`n`n" }
}
[System.IO.File]::WriteAllText($codexPath, $existing + $codexConfig)
Write-Host "OK  .codex/config.toml (full config)" -ForegroundColor Green
$count++

if ($env:BABA_STAGE_ADAPTERS -in @('1', 'true', 'yes')) {
    Write-Host "`nStaging generated adapter files..." -ForegroundColor Yellow
    Push-Location -LiteralPath $scriptDir
    try {
        $paths = @(
            '.claude\agents',
            '.claude\commands',
            '.cursor\rules',
            '.codex\config.toml',
            '.mcp.json'
        )
        foreach ($p in $paths) {
            if (Test-Path -LiteralPath $p) {
                git add $p
            }
        }
    }
    finally {
        Pop-Location
    }
    Write-Host "  OK" -ForegroundColor Green
}

Write-Host "`nDone. $count generated files." -ForegroundColor White
